# Generated by Django 3.2 on 2021-04-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20210418_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='conf_senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
