# Generated by Django 3.2 on 2021-04-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_pagamento', '0001_initial'),
        ('tipo_entrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_entrega.tipo_entrega')),
                ('tipo_pagamento_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_pagamento.tipo_pagamento')),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'db_table': 'item',
            },
        ),
    ]
