# Generated by Django 3.2 on 2021-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipo_entrega_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipo_pagamento_id',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
