# Generated by Django 3.2 on 2021-04-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210418_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.FloatField(default=1, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
