# Generated by Django 3.2 on 2021-04-19 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('item', '0003_item_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
