# Generated by Django 3.2 on 2021-04-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
    ]
