# Generated by Django 3.2 on 2021-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_arquivo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='arquivo_video',
            field=models.CharField(max_length=255, verbose_name='Vídeo'),
        ),
    ]
