# Generated by Django 3.2 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('arquivo_imagem', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Imagem')),
                ('arquivo_video', models.FileField(blank=True, max_length=254, null=True, upload_to='banner', verbose_name='Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
