# Generated by Django 3.2 on 2021-04-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
