# Generated by Django 3.2 on 2021-04-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_entrega', '0001_initial'),
        ('tipo_pagamento', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_entrega.tipo_entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pagamento_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_pagamento.tipo_pagamento'),
            preserve_default=False,
        ),
    ]
